server:
  port: 8080

spring:
  application:
    name: consumer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/consumer
    username: admin
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  data:
    redis:
      host: localhost
      port: 6379


